---
abstract: "YAML Ain't Markup Language (tm)"
author:
  - 'Ingy dot Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  perl: 5.8.1
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/YAML
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/YAML
version: 0.72
